"""Local-only Phase 1 job control around the canonical video pipeline."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

from video_factory.pipeline.errors import FactoryContractError
from video_factory.pipeline.export import write_json

from .config import PROJECT_ROOT
from .db import CandidateStore
from .phase1_local import load_local_brief
from .state import next_state
from .reference_video import (
    POLICY_VERSION,
    REFERENCE_RUNTIME_ROOT,
    analyze_reference,
    brief_digest,
    build_original_brief,
    ingest_reference,
    load_reference_bundle,
    stable_reference_job_key,
    write_original_brief,
)


STATE_ROOT = PROJECT_ROOT / "state" / "phase1_local"
DATABASE_PATH = STATE_ROOT / "phase1_jobs.sqlite3"
INPUT_ROOT = STATE_ROOT / "inputs"


def _emit(payload: dict[str, Any], code: int = 0) -> int:
    print(json.dumps(payload, ensure_ascii=False, sort_keys=True))
    return code


def _parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(prog="factory.py phase1")
    commands = root.add_subparsers(dest="command", required=True)
    commands.add_parser("doctor")
    commands.add_parser("init-db")
    create = commands.add_parser("create-topic")
    create.add_argument("--brief", type=Path, required=True)
    create.add_argument("--idempotency-key")
    reference = commands.add_parser("create-reference")
    reference.add_argument("--video", type=Path, required=True)
    reference.add_argument("--brief", type=Path, required=True)
    reference.add_argument("--rights", type=Path, required=True)
    reference.add_argument("--idempotency-key")
    run = commands.add_parser("run")
    run.add_argument("--job-id", required=True)
    status = commands.add_parser("status")
    status.add_argument("--job-id", required=True)
    cancel = commands.add_parser("cancel")
    cancel.add_argument("--job-id", required=True)
    retry = commands.add_parser("retry")
    retry.add_argument("--job-id", required=True)
    return root


def _store() -> CandidateStore:
    store = CandidateStore(DATABASE_PATH)
    store.initialize()
    return store


def _persist_brief(brief: dict[str, Any]) -> Path:
    digest = str(brief["factual_brief"]["topic_digest"])
    target = INPUT_ROOT / f"{digest}.json"
    if target.exists() and target.is_symlink():
        raise FactoryContractError(
            "phase1_input_path_invalid",
            "Phase 1 input storage cannot be a link.",
            {"reason": "reparse"},
        )
    write_json(target, brief)
    return target


def _create_topic(args: argparse.Namespace) -> dict[str, Any]:
    brief = load_local_brief(args.brief)
    persisted = _persist_brief(brief)
    digest = str(brief["factual_brief"]["topic_digest"])
    key = args.idempotency_key or f"phase1-topic:{digest}"
    store = _store()
    result = store.create_job(
        "local_topic",
        key,
        "video_factory_local_brief",
        str(brief["topic"]),
        requested_duration_seconds=int(brief.get("duration_target_seconds", 40)),
        metadata={
            "brief_path": persisted.relative_to(PROJECT_ROOT).as_posix(),
            "topic_digest": digest,
            "input_mode": str(brief["input_mode"]),
        },
    )
    return {"status": "created" if result["created"] else "existing", "job": result}


def _create_reference(args: argparse.Namespace) -> dict[str, Any]:
    user_brief = load_local_brief(args.brief)
    if user_brief.get("input_mode") != "topic":
        raise FactoryContractError(
            "reference_brief_invalid",
            "create-reference requires a topic-mode user brief; the original brief is generated by the analyzer.",
            {"field": "input_mode"},
        )
    bundle = ingest_reference(args.video, args.rights)
    report = analyze_reference(bundle)
    original = build_original_brief(user_brief, report)
    original_path = write_original_brief(bundle, original)
    source_sha = str(bundle["source_sha256"])
    canonical_key = stable_reference_job_key(source_sha, original)
    render_job_digest = hashlib.sha256(canonical_key.encode("utf-8")).hexdigest()[:24]
    render_job_id = f"phase1_ref_{render_job_digest}"
    requested_duration = int(original["reference_abstraction"]["duration_target_seconds"])
    runtime_root = Path(bundle["runtime_root"])
    metadata = {
        "brief_path": original_path.relative_to(PROJECT_ROOT).as_posix(),
        "runtime_root": runtime_root.relative_to(PROJECT_ROOT).as_posix(),
        "reference_id": str(bundle["reference_id"]),
        "source_sha256": source_sha,
        "brief_digest": brief_digest(original),
        "analyzer_policy_version": POLICY_VERSION,
        "analysis_verified": True,
        "render_job_id": render_job_id,
        "requested_idempotency_key": args.idempotency_key,
        "input_mode": "local_reference",
    }
    store = _store()
    result = store.create_job(
        "local_reference",
        canonical_key,
        "video_factory_local_reference",
        str(original["topic"]),
        requested_duration_seconds=requested_duration,
        metadata=metadata,
    )
    return {
        "status": "created" if result["created"] else "existing",
        "job": result,
        "reference": {
            "reference_id": bundle["reference_id"],
            "source_sha256": source_sha,
            "report": (runtime_root / "reference_report.json").relative_to(PROJECT_ROOT).as_posix(),
            "original_brief": original_path.relative_to(PROJECT_ROOT).as_posix(),
        },
    }


def _advance_to_rendering(store: CandidateStore, job_id: str) -> dict[str, Any]:
    job = store.status(job_id)
    while job["state"] != "RENDERING":
        target = next_state(str(job["state"]))
        if target is None:
            raise FactoryContractError(
                "phase1_job_state_invalid",
                "Phase 1 job cannot enter rendering from its current state.",
                {"state": str(job["state"])},
            )
        job = store.advance(job_id, target, reason="local_stage_completed")
    return job


def _run_job(args: argparse.Namespace) -> dict[str, Any]:
    from generate_video import run_local_brief

    store = _store()
    job = store.status(args.job_id)
    if job["state"] == "PENDING_REVIEW":
        return {
            "status": "pending_review",
            "job": job,
            "artifacts": store.artifacts(args.job_id),
            "idempotent": True,
        }
    if job["state"] in {"FAILED", "CANCELLED"}:
        raise FactoryContractError(
            "phase1_job_retry_required",
            "A failed or cancelled Phase 1 job must be retried explicitly.",
            {"state": str(job["state"])},
        )
    metadata = dict(job["metadata"])
    brief_ref = str(metadata.get("brief_path", ""))
    brief_path = (PROJECT_ROOT / brief_ref).resolve()
    if PROJECT_ROOT.resolve() not in brief_path.parents or not brief_path.is_file():
        raise FactoryContractError(
            "phase1_input_path_invalid",
            "The persisted Phase 1 brief is unavailable.",
            {"reason": "missing"},
        )
    _advance_to_rendering(store, args.job_id)
    try:
        reference_bundle = None
        reference_context = None
        if str(metadata.get("input_mode", "")) == "local_reference":
            runtime_ref = str(metadata.get("runtime_root", ""))
            runtime_root = (PROJECT_ROOT / runtime_ref).resolve()
            reference_bundle = load_reference_bundle(runtime_root, expected_source_sha256=str(metadata.get("source_sha256", "")))
            reference_bundle["job_id"] = str(metadata.get("render_job_id", ""))
            reference_context = {
                "source_sha256": str(metadata.get("source_sha256", "")),
                "policy_version": str(metadata.get("analyzer_policy_version", "")),
                "analysis_verified": bool(metadata.get("analysis_verified", False)),
            }
        result = run_local_brief(
            brief_path,
            emit=False,
            reference_context=reference_context,
            reference_bundle=reference_bundle,
        )
        store.advance(args.job_id, "QUALITY_CHECK", reason="local_render_completed")
        final_job = store.advance(args.job_id, "PENDING_REVIEW", reason="local_quality_passed")
        for artifact_type, value in {
            "final_master": result["output"],
            "review_package": result["review_package"],
        }.items():
            path = Path(str(value)).resolve()
            store.record_artifact(
                args.job_id,
                artifact_type,
                path.relative_to(PROJECT_ROOT).as_posix(),
                hashlib.sha256(path.read_bytes()).hexdigest(),
            )
        return {
            "status": "pending_review",
            "job": final_job,
            "artifacts": store.artifacts(args.job_id),
            "result": result,
        }
    except Exception:
        current = store.status(args.job_id)
        if current["state"] not in {"FAILED", "CANCELLED", "PENDING_REVIEW"}:
            store.fail(args.job_id, "phase1_local_execution_failed")
        raise


def main(arguments: list[str] | None = None) -> int:
    args = _parser().parse_args(arguments)
    try:
        if args.command == "doctor":
            return _emit(
                {
                    "status": "ok",
                    "mode": "phase1_local_only",
                    "canonical_video_entrypoint": "generate_video.py --local-brief",
                    "database": DATABASE_PATH.relative_to(PROJECT_ROOT).as_posix(),
                    "provider_enabled": False,
                    "feishu_enabled": False,
                    "cron_enabled": False,
                }
            )
        if args.command == "init-db":
            _store()
            return _emit({"status": "initialized", "database": DATABASE_PATH.relative_to(PROJECT_ROOT).as_posix()})
        if args.command == "create-topic":
            return _emit(_create_topic(args))
        if args.command == "create-reference":
            return _emit(_create_reference(args))
        if args.command == "run":
            return _emit(_run_job(args))
        if args.command == "status":
            store = _store()
            return _emit(
                {
                    "status": "ok",
                    "job": store.status(args.job_id),
                    "events": store.events(args.job_id),
                    "artifacts": store.artifacts(args.job_id),
                }
            )
        if args.command == "cancel":
            return _emit({"status": "cancelled", "job": _store().cancel(args.job_id, "user_requested")})
        if args.command == "retry":
            return _emit({"status": "retry_ready", "job": _store().retry(args.job_id, "user_requested")})
    except FactoryContractError as exc:
        return _emit({"status": "error", "error": exc.to_dict()}, 2)
    except KeyError:
        return _emit(
            {
                "status": "error",
                "error": {
                    "code": "phase1_job_not_found",
                    "message": "The Phase 1 job was not found.",
                    "context": {},
                },
            },
            2,
        )
    except (OSError, ValueError, RuntimeError):
        return _emit(
            {
                "status": "error",
                "error": {
                    "code": "phase1_local_execution_failed",
                    "message": "The local Phase 1 operation failed.",
                    "context": {},
                },
            },
            2,
        )
    raise AssertionError(f"unsupported_command:{args.command}")


__all__ = ["main"]
