import crypto from 'node:crypto';import fs from 'node:fs/promises';import path from 'node:path';import process from 'node:process';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const req=createRequire(path.join(ROOT,'remotion','package.json'));const {bundle}=req('@remotion/bundler');const {renderMedia,renderStill,selectComposition}=req('@remotion/renderer');const ts=req.resolve('typescript');req(ts);req.cache[ts].exports=req('typescript-remotion');
const FLAGS=['--scene-plan','--timing-manifest','--output','--report','--stills-dir','--clips-dir'];const CHROME=['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'];const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const execFileAsync=promisify(execFile);async function stripAudio(raw,output){await execFileAsync('ffmpeg',['-y','-nostdin','-v','error','-i',raw,'-map','0:v:0','-c:v','copy','-an',output],{timeout:300000});await fs.rm(raw,{force:true});}
function args(argv){const out={};for(let i=0;i<argv.length;i+=2){if(!FLAGS.includes(argv[i])||out[argv[i]]||!argv[i+1]||argv[i+1].startsWith('--'))throw Error('arguments_invalid');out[argv[i]]=argv[i+1];}if(FLAGS.some(k=>!out[k]))throw Error('arguments_required');return out;}
async function chrome(){for(const value of CHROME){try{if((await fs.stat(value)).isFile())return value;}catch{}}throw Error('approved_chrome_missing');}
function eDrive(value){const resolved=path.resolve(value);if(!/^E:[\\/]/i.test(resolved))throw Error('output_must_use_e_drive');return resolved;}
function build(plan,timing){if(plan.schema_version!=='1.0'||timing.schema_version!=='1.0'||!Array.isArray(plan.scenes)||!Array.isArray(timing.segments)||plan.scenes.length!==timing.segments.length)throw Error('visual_input_invalid');if(plan.script_sha256!==timing.script?.sha256)throw Error('script_hash_mismatch');let end=0;const scenes=plan.scenes.map((scene,i)=>{const seg=timing.segments[i],start=Number(seg.scene_start_microseconds)/1e6,finish=Number(seg.scene_end_microseconds)/1e6;if(seg.index!==i+1||scene.scene_index!==i+1||start!==end||finish<=start)throw Error('scene_boundaries_not_contiguous');end=finish;return {...scene,start_seconds:start,end_seconds:finish};});if(Math.abs(end-Number(timing.visual_duration_seconds))>.000001)throw Error('visual_duration_mismatch');return {schema_version:'1.0',title:String(plan.title||plan.script_id),aspect:plan.aspect||'16:9',fps:30,duration_seconds:end,scenes};}
async function main(){const a=args(process.argv.slice(2)),planPath=path.resolve(a['--scene-plan']),timingPath=path.resolve(a['--timing-manifest']),output=eDrive(a['--output']),report=eDrive(a['--report']),stills=eDrive(a['--stills-dir']),clips=eDrive(a['--clips-dir']);const planBytes=await fs.readFile(planPath),timingBytes=await fs.readFile(timingPath),plan=JSON.parse(planBytes),timing=JSON.parse(timingBytes);if(timing.scene_plan?.sha256!==sha(planBytes))throw Error('scene_plan_hash_mismatch');const inputProps=build(plan,timing);await Promise.all([fs.mkdir(path.dirname(output),{recursive:true}),fs.mkdir(path.dirname(report),{recursive:true}),fs.mkdir(stills,{recursive:true}),fs.mkdir(clips,{recursive:true})]);const browserExecutable=await chrome(),serveUrl=await bundle({entryPoint:path.join(ROOT,'remotion','src','index.ts')}),composition=await selectComposition({serveUrl,id:'TechnicalExplainer',inputProps,browserExecutable});const artifacts=[];
 for(const scene of inputProps.scenes){const start=Math.round(scene.start_seconds*30),end=Math.round(scene.end_seconds*30)-1,mid=Math.floor((start+end)/2),still=path.join(stills,`scene_${String(scene.scene_index).padStart(2,'0')}_mid.png`),clip=path.join(clips,`scene_${String(scene.scene_index).padStart(2,'0')}.mp4`),raw=`${clip}.raw.mp4`;await renderStill({composition,serveUrl,inputProps,frame:mid,output:still,browserExecutable,imageFormat:'png',logLevel:'error'});await renderMedia({composition,serveUrl,inputProps,outputLocation:raw,browserExecutable,codec:'h264',concurrency:1,logLevel:'warn',frameRange:[start,end]});await stripAudio(raw,clip);artifacts.push({scene_index:scene.scene_index,visual_type:scene.visual_type,start_seconds:scene.start_seconds,end_seconds:scene.end_seconds,still:{filename:path.relative(path.dirname(report),still).replaceAll('\\','/'),sha256:sha(await fs.readFile(still)),frame:mid},clip:{filename:path.relative(path.dirname(report),clip).replaceAll('\\','/'),sha256:sha(await fs.readFile(clip))}});}
 const rawOutput=`${output}.raw.mp4`;await renderMedia({composition,serveUrl,inputProps,outputLocation:rawOutput,browserExecutable,codec:'h264',concurrency:1,logLevel:'warn'});await stripAudio(rawOutput,output);const landscape=inputProps.aspect==='16:9',value={schema_version:'1.0',status:'passed',renderer:'remotion',composition:'TechnicalExplainer',input:{scene_plan_filename:path.basename(planPath),scene_plan_sha256:sha(planBytes),timing_manifest_filename:path.basename(timingPath),timing_manifest_sha256:sha(timingBytes),script_sha256:plan.script_sha256},visual:{filename:path.relative(path.dirname(report),output).replaceAll('\\','/'),sha256:sha(await fs.readFile(output)),width:landscape?1920:1080,height:landscape?1080:1920,fps:30,duration_seconds:inputProps.duration_seconds,audio_present:false,burned_in_subtitles:false,scene_timing:artifacts},layout_contract:{version:'1.0',aspect:inputProps.aspect,safe_area:landscape?{left:84,right:84,top:58,bottom:210}:{left:72,right:72,top:84,bottom:360},subtitle_reserve:landscape?{top:870,height:150}:{top:1560,height:240},text_policy:'bounded_natural_wrap',overflow_policy:'fail_closed',theme_token:'technical_neutral',background_is_theme_driven:true,pink_global_background:false,data_layout_box:true},mascot:{mode:'off',present:false},outputs_on_e_drive:true};await fs.writeFile(report,JSON.stringify(value,null,2)+'\n');console.log(JSON.stringify(value));}
main().catch(error=>{console.error(error instanceof Error?error.message:'render_failed');process.exitCode=1;});
