import React from 'react';
import {fillTextBox, fitText, measureText} from '@remotion/layout-utils';
import {AbsoluteFill, Easing, interpolate, spring, useCurrentFrame, useVideoConfig} from 'remotion';

export type TechnicalScene = {start_seconds:number; end_seconds:number; scene_index:number; visual_type:'kinetic_typography'|'system_diagram'|'timeline'|'comparison_card'|'checklist'; narration:string; on_screen_knowledge:string; information_role:string; narrative_role:string; shot_intent:string; motion:string; transition:string; source_refs:string[]};
export type TechnicalExplainerInput = {schema_version:'1.0'; title:string; aspect:'16:9'|'9:16'; fps:30; duration_seconds:number; scenes:TechnicalScene[]};
export const ASPECT_GEOMETRY={'16:9':{titleMaxWidth:1450,sceneWidth:1752,titleMinFont:42,titleMaxFont:58,itemMinFont:24},'9:16':{titleMaxWidth:900,sceneWidth:936,titleMinFont:40,titleMaxFont:54,itemMinFont:22}} as const;
type SceneTextLayout={mainFontSize:number;itemFontSizes:number[];itemBoxWidth:number;maxLines:number;minFontSize:number;maxFontSize:number;columns:number};

const palette={canvas:'#F2F4F7',ink:'#172033',muted:'#647087',panel:'#FFFFFF',line:'#CCD5E1',blue:'#3578D4',teal:'#2A9D8F',amber:'#E29A32'};
const FONT='Microsoft YaHei';
const clamp={extrapolateLeft:'clamp' as const,extrapolateRight:'clamp' as const};
const Box:React.FC<{children:React.ReactNode;style?:React.CSSProperties}>=({children,style})=><div style={{background:palette.panel,border:`2px solid ${palette.line}`,borderRadius:24,padding:28,...style}}>{children}</div>;

const Grammar:React.FC<{scene:TechnicalScene;layout:SceneTextLayout;local:number;fps:number}>=({scene,layout,local,fps})=>{
 const reveal=interpolate(local,[0,Math.min(24,fps)],[0,1],{...clamp,easing:Easing.bezier(.16,1,.3,1)});
 const words=scene.on_screen_knowledge.split(/[，。；:：]/).filter(Boolean).slice(0,4);
 if(scene.visual_type==='kinetic_typography') return <div data-layout-box="knowledge-kinetic" style={{fontSize:layout.mainFontSize,fontWeight:950,lineHeight:1.18,maxWidth:layout.itemBoxWidth,opacity:reveal,translate:`0 ${(1-reveal)*32}px`}}>{scene.on_screen_knowledge}</div>;
 if(scene.visual_type==='system_diagram') return <div style={{display:'grid',gridTemplateColumns:`repeat(${layout.columns},minmax(0,1fr))`,alignItems:'stretch',gap:20,width:'100%'}}>{words.map((w,i)=><Box key={w} style={{fontSize:layout.itemFontSizes[i],fontWeight:900,opacity:interpolate(local,[i*8,i*8+18],[0,1],clamp),minWidth:0}}><span data-layout-box={`system-node-${i}`}>{w}</span></Box>)}</div>;
 if(scene.visual_type==='timeline') return <div style={{display:'grid',gridTemplateColumns:`repeat(${layout.columns},minmax(0,1fr))`,gap:18,width:'100%'}}>{words.map((w,i)=><Box key={w} style={{borderTop:`9px solid ${[palette.blue,palette.teal,palette.amber][i%3]}`,opacity:interpolate(local,[i*9,i*9+18],[0,1],clamp)}}><b style={{fontSize:22}}>0{i+1}</b><div data-layout-box={`timeline-node-${i}`} style={{fontSize:layout.itemFontSizes[i],fontWeight:900,marginTop:24}}>{w}</div></Box>)}</div>;
 if(scene.visual_type==='comparison_card') return <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:28,width:'100%'}}><Box style={{borderTop:`9px solid ${palette.blue}`,fontSize:34,fontWeight:900}}>条件<br/><span data-layout-box="comparison-condition" style={{fontSize:layout.itemFontSizes[0],color:palette.muted}}>{words[0]??scene.information_role}</span></Box><Box style={{borderTop:`9px solid ${palette.teal}`,fontSize:34,fontWeight:900}}>结果<br/><span data-layout-box="comparison-result" style={{fontSize:layout.itemFontSizes[1]??layout.itemFontSizes[0],color:palette.muted}}>{words.slice(1).join(' · ')||scene.on_screen_knowledge}</span></Box></div>;
 return <div style={{display:'grid',gap:15,width:'100%'}}>{words.map((w,i)=><Box key={w} style={{display:'flex',gap:20,alignItems:'center',opacity:interpolate(local,[i*8,i*8+16],[0,1],clamp)}}><span style={{color:palette.teal,fontSize:34,fontWeight:950}}>✓</span><span data-layout-box={`checklist-item-${i}`} style={{fontSize:layout.itemFontSizes[i],fontWeight:850}}>{w}</span></Box>)}</div>;
};

const fitBox=(text:string,width:number,maxLines:number,minFont:number,maxFont:number)=>{fitText({text,withinWidth:width,fontFamily:FONT,fontWeight:900});for(let fontSize=maxFont;fontSize>=minFont;fontSize--){const measured=measureText({text,fontFamily:FONT,fontSize,fontWeight:900});if(!Number.isFinite(measured.width)||!Number.isFinite(measured.height))throw new Error('layout_measurement_invalid');const box=fillTextBox({maxBoxWidth:width,maxLines});let overflow=false;for(const character of Array.from(text)){if(box.add({text:character,fontFamily:FONT,fontSize,fontWeight:900}).exceedsBox){overflow=true;break;}}if(!overflow)return fontSize;}throw new Error('layout_text_cannot_fit');};
export const calculateTextLayout=(value:TechnicalExplainerInput)=>{const geometry=ASPECT_GEOMETRY[value.aspect],portrait=value.aspect==='9:16',titleFontSize=fitBox(value.title,geometry.titleMaxWidth,2,geometry.titleMinFont,geometry.titleMaxFont);const scenes:SceneTextLayout[]=value.scenes.map(scene=>{const parts=scene.on_screen_knowledge.split(/[，。；;:：]/).filter(Boolean).slice(0,4),items=parts.length?parts:[scene.on_screen_knowledge],count=items.length;let columns=1,itemBoxWidth=Math.min(1200,geometry.sceneWidth),maxLines=3,maxFontSize=portrait?54:68;if(scene.visual_type==='system_diagram'||scene.visual_type==='timeline'){columns=portrait?Math.min(2,count):count;itemBoxWidth=(geometry.sceneWidth-(columns-1)*20)/columns-56;maxFontSize=30;}if(scene.visual_type==='comparison_card'){columns=2;itemBoxWidth=(geometry.sceneWidth-28)/2-56;maxFontSize=27;}if(scene.visual_type==='checklist'){itemBoxWidth=geometry.sceneWidth-96;maxLines=2;maxFontSize=29;}const itemFontSizes=items.map(part=>fitBox(part,itemBoxWidth,maxLines,geometry.itemMinFont,maxFontSize));return {mainFontSize:fitBox(scene.on_screen_knowledge,itemBoxWidth,maxLines,geometry.itemMinFont,maxFontSize),itemFontSizes,itemBoxWidth,maxLines,minFontSize:geometry.itemMinFont,maxFontSize,columns};});return {method:'layout-utils:measureText+fitText+fillTextBox',geometry,titleFontSize,scenes,limits:{title:{maxLines:2,minFontSize:geometry.titleMinFont},knowledge:{maxLines:3,minFontSize:geometry.itemMinFont}}};};
export const validateTechnicalExplainer=(value:TechnicalExplainerInput)=>{if(value.schema_version!=='1.0'||value.fps!==30||!['16:9','9:16'].includes(value.aspect)||!Array.isArray(value.scenes)||value.scenes.length<5||!value.title.trim()||value.title.length>80)throw new Error('technical_explainer_input_invalid');let end=0;for(const [i,s] of value.scenes.entries()){const hook=s.scene_index===1&&s.narrative_role==='hook'&&s.information_role==='hook_question';if(s.scene_index!==i+1||s.start_seconds!==end||s.end_seconds<=s.start_seconds||!s.on_screen_knowledge.trim()||s.on_screen_knowledge.length>(value.aspect==='16:9'?120:90)||(!hook&&!s.source_refs.length)||(hook&&s.source_refs.length))throw new Error('technical_explainer_scene_invalid');end=s.end_seconds;}if(Math.abs(end-value.duration_seconds)>.001)throw new Error('technical_explainer_duration_invalid');calculateTextLayout(value);return value;};

export const TechnicalExplainer:React.FC<TechnicalExplainerInput>=(input)=>{const frame=useCurrentFrame();const {fps}=useVideoConfig();const textLayout=calculateTextLayout(input);const seconds=frame/fps;const index=Math.max(0,input.scenes.findIndex(s=>seconds>=s.start_seconds&&seconds<s.end_seconds));const scene=input.scenes[index]??input.scenes.at(-1)!;const local=Math.max(0,frame-Math.round(scene.start_seconds*fps));const entrance=spring({frame:local,fps,config:{damping:180}});const portrait=input.aspect==='9:16';return <AbsoluteFill style={{boxSizing:'border-box',background:palette.canvas,color:palette.ink,fontFamily:`${FONT}, sans-serif`,padding:portrait?'84px 72px 360px':'58px 84px 210px'}}>
 <div data-layout-box="eyebrow" style={{fontSize:18,fontWeight:900,letterSpacing:2,color:palette.blue}}>TECHNICAL EXPLAINER · VISUAL ONLY</div>
 <div data-layout-box="title" style={{fontSize:textLayout.titleFontSize,fontWeight:950,lineHeight:1.15,maxWidth:textLayout.geometry.titleMaxWidth,marginTop:18}}>{input.title}</div>
 <div style={{height:5,background:palette.line,marginTop:30}}><div style={{height:'100%',width:`${interpolate(seconds,[0,input.duration_seconds],[0,100],clamp)}%`,background:palette.blue}}/></div>
 <div data-layout-box={`scene-${scene.scene_index}-knowledge`} style={{flex:1,display:'flex',alignItems:'center',opacity:entrance,marginTop:38,width:textLayout.geometry.sceneWidth}}><Grammar scene={scene} layout={textLayout.scenes[index]} local={local} fps={fps}/></div>
 <div style={{fontSize:17,color:palette.muted,display:'flex',justifyContent:'space-between'}}><span data-layout-box="roles">{scene.information_role} · {scene.narrative_role}</span><span data-layout-box="counter">{scene.scene_index}/{input.scenes.length} · mascot absent · native-caption reserve</span></div>
 </AbsoluteFill>;};
